version: "3"

services:

  db:
    image: mariadb:10.7
    networks:
      - adimeo
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/html/
    networks:
      - adimeo
    links:
      - db

  nginx:
    build: docker/nginx
    volumes:
      - .:/var/www/html/
    ports:
      - "${APP_PORT}:80"
    networks:
      - adimeo
    depends_on:
      - php


networks:
  adimeo:
